# 存放路径：项目根目录/.gitee/workflows/build.yml
name: 自动编译32位(x86)exe程序
on:
  workflow_dispatch:  # 手动触发（唯一正确方式）

jobs:
  build-windows-x86:
    runs-on: windows-latest  # 云端Windows系统（编译exe必须用这个）
    defaults:
      run:
        shell: cmd
    
    steps:
      - name: 拉取项目源码
        uses: actions/checkout@v4

      # 安装32位 Python3.8
      - name: 安装 Python3.8 x86
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"
          architecture: "x86"

      # 安装uv
      - name: 安装 uv
        run: pip install uv

      # 用uv安装依赖（无requirements.txt）
      - name: uv安装依赖
        run: |
          cd project-bulid
          uv sync

      # 安装Nuitka
      - name: 安装 Nuitka
        run: pip install nuitka

      # 执行你的编译命令
      - name: Nuitka 编译32位exe
        run: |
          cd project-bulid/app
          nuitka --standalone --output-dir=../dist --plugin-enable=tk-inter --show-progress --show-memory --include-data-dir=./config=config --include-data-dir=./static=static --mingw64 main.py

      # 上传exe文件
      - name: 上传编译产物
        uses: actions/upload-artifact@v4
        with:
          name: auto-work-bdc-32位
          path: dist/